# Complex Indexing

In [1]:
import numpy as np
import csv

In [2]:
a = np.arange(12) ** 2
print(a)

[  0   1   4   9  16  25  36  49  64  81 100 121]


In [3]:
index_1 = [2, 6, 8]
a[index_1]

array([ 4, 36, 64])

In [4]:
index_2 = np.array([[2,4], [8,10]])

In [5]:
# shape 1d to 2d by indexing

a[index_2]

array([[  4,  16],
       [ 64, 100]])

In [6]:
food = [
    ['blueberry', 'strawberry', 'cherry', 'blackberry'], 
    ['pine nut', 'hazelnut',  'pecan', 'cocnut'], 
    ['mustard', 'paprika', 'nutmeg', 'clove']]

food = np.array(food)

In [7]:
food_row_idx = np.array([[0,0], [2, 2]])
food_col_idx = np.array([[0,3], [0,3]])

food[food_row_idx, food_col_idx]

array([['blueberry', 'blackberry'],
       ['mustard', 'clove']], 
      dtype='<U10')

# Structured Data

In [9]:
name = ["Rza", "Gza", "ODB", "U-God"]
student_id = [1, 2, 3, 4]
score = [89.1, 99.9, 40.4, 25.0 ]

student_data = np.zeros(4, dtype={'names': ('name', 'student_id', 'score'), 'formats': ('U10', 'i4', 'f8')})
student_data

array([('', 0, 0.0), ('', 0, 0.0), ('', 0, 0.0), ('', 0, 0.0)], 
      dtype=[('name', '<U10'), ('student_id', '<i4'), ('score', '<f8')])

In [10]:
# Set col values
student_data['name'] = name
student_data['student_id'] = student_id
student_data['score'] = score

student_data

array([('Rza', 1, 89.1), ('Gza', 2, 99.9), ('ODB', 3, 40.4),
       ('U-God', 4, 25.0)], 
      dtype=[('name', '<U10'), ('student_id', '<i4'), ('score', '<f8')])

In [12]:
# Use boolean expression to select names based on scores 
student_data[student_data['score'] > 50]['name']

array(['Rza', 'Gza'], 
      dtype='<U10')

# Broadcasting

Working with arrays of different shapes
Shape of the smaller array must be compatible. It should be replicable to for the shape of the other. The last dim should be 1, and the other should match the larger array.

In [14]:
heights = [165, 170, 168, 172, 169]
weights = [61, 76, 81, 62, 60]
student_bio = np.array([heights, weights])
student_bio

array([[165, 170, 168, 172, 169],
       [ 61,  76,  81,  62,  60]])

In [16]:
# convert heights to inches and weights to pounds using matrix operations
# This shape won't work bc the data is a 1D array
converter_1 = np.array([0.0328084, 2.20462])
converter_1

array([ 0.0328084,  2.20462  ])

In [17]:
student_bio * converter_1

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [22]:
# This will work (2D array)
converter_2 = np.reshape(converter_1, (2, 1))
converter_2

array([[ 0.0328084],
       [ 2.20462  ]])

In [23]:
student_bio * converter_2

array([[   5.413386 ,    5.577428 ,    5.5118112,    5.6430448,
           5.5446196],
       [ 134.48182  ,  167.55112  ,  178.57422  ,  136.68644  ,  132.2772   ]])

# Reshape

-1 means that that this dim is unknow so fit automagically

In [28]:
# 1d to 2, 5, 3
foo = np.arange(30)
foo.shape = 2,-1,3
foo

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [29]:
# using reshape function
bar = np.arange(30)
np.reshape(bar, (2, -1, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

# Stacking

Joining arrays along a specified axis, zero by default

In [37]:
baz = np.array([['alpha', 'beta'], ['gamma', 'delta']])
bez = np.array([['alef', 'bet'], ['gimel', 'dalet']])

In [38]:
np.concatenate([baz, bez])

array([['alpha', 'beta'],
       ['gamma', 'delta'],
       ['alef', 'bet'],
       ['gimel', 'dalet']], 
      dtype='<U5')

In [39]:
np.concatenate([baz, bez], axis=1)

array([['alpha', 'beta', 'alef', 'bet'],
       ['gamma', 'delta', 'gimel', 'dalet']], 
      dtype='<U5')

In [53]:
np.stack([baz, bez], axis=0)

array([[['alpha', 'beta'],
        ['gamma', 'delta']],

       [['alef', 'bet'],
        ['gimel', 'dalet']]], 
      dtype='<U5')

In [54]:
np.vstack([baz, bez])

array([['alpha', 'beta'],
       ['gamma', 'delta'],
       ['alef', 'bet'],
       ['gimel', 'dalet']], 
      dtype='<U5')

In [55]:
np.stack([baz, bez], axis=1)

array([[['alpha', 'beta'],
        ['alef', 'bet']],

       [['gamma', 'delta'],
        ['gimel', 'dalet']]], 
      dtype='<U5')

In [56]:
np.hstack([baz, bez])

array([['alpha', 'beta', 'alef', 'bet'],
       ['gamma', 'delta', 'gimel', 'dalet']], 
      dtype='<U5')

# Misc Functions

np.argsort - returns sorted indexes along an axis, can specify the sort algorithm
np.argmax, np.argmin - returns indexes of max | min
np.where - returns indexes based on a boolean condition
np.mean - get an avg from an array
np.extract - arg1 conditional expression, arg2 array - use to get values from arg2 using arg1
np.vectorize - will allow a function for scalars to be applied to vectors