# Complex Indexing

In [2]:
import numpy as np
import csv

In [3]:
a = np.arange(12) ** 2
print(a)

[  0   1   4   9  16  25  36  49  64  81 100 121]


In [4]:
index_1 = [2, 6, 8]
a[index_1]

array([ 4, 36, 64])

In [5]:
index_2 = np.array([[2,4], [8,10]])

In [6]:
# shape 1d to 2d by indexing

a[index_2]

array([[  4,  16],
       [ 64, 100]])

In [7]:
food = [
    ['blueberry', 'strawberry', 'cherry', 'blackberry'], 
    ['pine nut', 'hazelnut',  'pecan', 'cocnut'], 
    ['mustard', 'paprika', 'nutmeg', 'clove']]

food = np.array(food)

In [11]:
food_row_idx = np.array([[0,0], [2, 2]])
food_col_idx = np.array([[0,3], [0,3]])

food[food_row_idx, food_col_idx]

array([['blueberry', 'blackberry'],
       ['mustard', 'clove']], 
      dtype='<U10')